<a href="https://colab.research.google.com/github/nidhales/python/blob/main/netflix_titles_filtre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd 
df=pd.read_csv("netflix_titles.csv")

In [3]:
df["rating"]

0       TV-MA
1       TV-MA
2           R
3       PG-13
4       PG-13
        ...
7782    TV-MA
7783    TV-14
7784    TV-MA
7785    TV-PG
7786    TV-MA
Name: rating, Length: 7787, dtype: object

In [4]:
df["rating"]=="TV-MA"

0        True
1        True
2       False
3       False
4       False
        ...
7782     True
7783    False
7784     True
7785    False
7786     True
Name: rating, Length: 7787, dtype: bool

In [5]:
df[df["rating"]=="TV-MA"]

     show_id  ...                                        description
0         s1  ...  In a future where the elite inhabit an island ...
1         s2  ...  After a devastating earthquake hits Mexico Cit...
5         s6  ...  A genetics professor experiments with a treatm...
6         s7  ...  After an awful accident, a couple admitted to ...
9        s10  ...  An architect and his wife move into a castle t...
...      ...  ...                                                ...
7779   s7780  ...  An assortment of talent takes the stage for a ...
7780   s7781  ...  A drug dealer starts having doubts about his t...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7784   s7785  ...  In this documentary, South African rapper Nast...
7786   s7787  ...  This documentary delves into the mystique behi...

[2863 rows x 12 columns]

In [6]:
country_filtre =df["country"].isin(["Mexico","Australia"])

In [7]:
df[country_filtre]

     show_id  ...                                        description
1         s2  ...  After a devastating earthquake hits Mexico Cit...
12       s13  ...  Archival video and new interviews examine Mexi...
137     s138  ...  This series examines the nature of cuteness an...
138     s139  ...  From fangs to claws to venomous stings, they a...
140     s141  ...  Get up close and personal with avalanches, fie...
...      ...  ...                                                ...
7734   s7735  ...  An ad creative and a successful exec have a gr...
7752   s7753  ...  It's drama Down Under when expectant mothers w...
7773   s7774  ...  This introspective rockumentary follows the ca...
7779   s7780  ...  An assortment of talent takes the stage for a ...
7785   s7786  ...  Dessert wizard Adriano Zumbo looks for the nex...

[183 rows x 12 columns]

In [12]:
df1=df.copy()
df1.type=df1.type.apply(lambda x:x.replace("$",""))
df1.rating

0       TV-MA
1       TV-MA
2           R
3       PG-13
4       PG-13
        ...
7782    TV-MA
7783    TV-14
7784    TV-MA
7785    TV-PG
7786    TV-MA
Name: rating, Length: 7787, dtype: object

In [10]:
df1.type

0       TV Show
1         Movie
2         Movie
3         Movie
4         Movie
         ...
7782      Movie
7783      Movie
7784      Movie
7785    TV Show
7786      Movie
Name: type, Length: 7787, dtype: object

In [14]:
df1.type=df1.type.astype(object)
df1[df1.type=="Movie"]

     show_id  ...                                        description
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
6         s7  ...  After an awful accident, a couple admitted to ...
...      ...  ...                                                ...
7781   s7782  ...  Dragged from civilian life, a former superhero...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7786   s7787  ...  This documentary delves into the mystique behi...

[5377 rows x 12 columns]

In [15]:
df1=df.copy()
df1.type=df1.type.apply(lambda x:x.replace("$",""))
df1.type=df1.type.astype(object)
df1[df1.type=="Movie"]

     show_id  ...                                        description
1         s2  ...  After a devastating earthquake hits Mexico Cit...
2         s3  ...  When an army recruit is found dead, his fellow...
3         s4  ...  In a postapocalyptic world, rag-doll robots hi...
4         s5  ...  A brilliant group of students become card-coun...
6         s7  ...  After an awful accident, a couple admitted to ...
...      ...  ...                                                ...
7781   s7782  ...  Dragged from civilian life, a former superhero...
7782   s7783  ...  When Lebanon's Civil War deprives Zozo of his ...
7783   s7784  ...  A scrappy but poor boy worms his way into a ty...
7784   s7785  ...  In this documentary, South African rapper Nast...
7786   s7787  ...  This documentary delves into the mystique behi...

[5377 rows x 12 columns]